### ISSUE TITLE
wheel_separation_x, wheel_separation_y parameters don`t work

### ISSUE THREAD

**Issue by max-kuzmin** [ridgeback/ridgeback#26]
I have found a bug with wheel_separation parameters.
You should take out these code block from outer "if" operator to make it work.
https://github.com/ridgeback/ridgeback/blob/69b9a899e87237f191f64f11a159e482dcb444ed/ridgeback_control/src/mecanum_drive_controller.cpp#L416-L424

**Comment by tonybaltovski** [comment]
Thanks, this was fixed.
