### ISSUE TITLE
Undefined substitution argument namespace

### ISSUE THREAD

**Issue by mbreyer** [ridgeback/ridgeback#36]
On the `kinetic-devel` branch, trying to load the robot description using

```
roslaunch ridgeback_description description.launch
```

leads to the following error:

```
Undefined substitution argument namespace
when processing file: /path/to/catkin_ws/src/ridgeback/ridgeback_description/urdf/ridgeback.gazebo
included from: /path/to/catkin_ws/src/ridgeback/ridgeback_description/urdf/ridgeback.urdf.xacro
```

It might be due to changes from b47792baf1956bb0121d8e33cee096c37804f8c9, which added a reference to a `namespace` argument, but does not seem to define it anywhere.

**Comment by tonybaltovski** [comment]
@mbreyer you are correct, I have removed it.  Thank you for catching this!

**Comment by mbreyer** [comment]
Thanks for the quick reply, but I think you still missed some references. I opened a pull request (#37) that reverts the commit that introduced them. This fixed the issue on my machine.

**Comment by tonybaltovski** [comment]
Thanks for your fix, I didn't see it and Jenkins caught it.

**Comment by mbreyer** [comment]
No worries, glad that it is fixed now.
