### ISSUE TITLE
Ridgeback does not move in simulation

### ISSUE THREAD

**Issue by uahic** [ridgeback/ridgeback#47]
I'm picking up  this question again as I dont fully understand how moving the ridgeback does work under the hood in Gazebo.

To my experimental knowledge the ridgeback does not move at all when the force-based plugin is removed (the wheels do spin due to the MecanumDriveController, however), but it seems not (enough) force is applied - if any. Enabling contact points in Gazebo reveals that all 4 wheel do have ground contact indeed. I cant move in any direction using the demo (melodic-devel) and steering via keyboard (or rviz marker server). So is the force plugin a 'cheat' in order to make it work in Gazebos physics engine (ODE in my case) or is there something I have overlooked? This should be documented clearly to avoid confusions for the users

Thank you very much in advance :)!

_Originally posted by @uahic in https://github.com/ridgeback/ridgeback/issues/29#issuecomment-1097185610_

**Comment by tonybaltovski** [comment]
The force plugin is indeed a cheat.

**Comment by uahic** [comment]
@tonybaltovski alright :) thanks
