### ISSUE TITLE
Ridgeback urdf does not move in Pybullet simulation engine

### ISSUE THREAD

**Issue by chenxing618** [ridgeback/ridgeback#49]
Hi. I used the Ridgeback urdf in Pybullet Gym engine. But I found that it can not move using any command to control the wheels. But i check the urdf file. The wheel is continuous. Why in the simulation the joint value is always zero. Really confused. Could you give me some idea on that?

Many Thanks for that!

**Comment by tonybaltovski** [comment]
I am not sure about the Pybullet Gym engine but for Gazebo, a plugin is used to control the wheels.

**Comment by chenxing618** [comment]
We successfully tested in Pybullet Gym now without plugin. It seems that the "front_rocker" axis shoud be around z axis not x axis. We changed that, then it worked.
